name: Hello World Training Workflow

on:
  workflow_dispatch:

env:
  MY_ENV: "Hello from env!"

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"

      - name: List files BEFORE checkout
        run: ls -l

      - name: Checkout
        uses: actions/checkout@v5

      - name: List files AFTER checkout
        run: ls -l

      - name: Run a multi-line script
        run: |
          echo "MY_ENV is: $MY_ENV"
          echo "GitHub Actor is: $GITHUB_ACTOR"
